"""add status column to moderations

Revision ID: ac22abb4b481
Revises: ccb4b9c25937
Create Date: 2026-05-29 02:00:54.608009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac22abb4b481'
down_revision: Union[str, Sequence[str], None] = 'ccb4b9c25937'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('moderations', sa.Column('status', sa.String(), nullable=False, server_default='pending'))
    op.alter_column('moderations', 'decision',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('moderations', 'decision',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('moderations', 'status')
    # ### end Alembic commands ###
